version: '3.8'

services:
  app:
    container_name: stores-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=3001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=nest
      - DB_SCHEMA=stores
      - DB_DIALECT=postgres
      - DB_USERNAME=fan
      - DB_PASSWORD=lupa_password
      - DB_SYNC=true
      - JWT_SECRET=whosyourdaddy
      - JWT_EXP=60m
    ports:
      - "3001:3001"
    depends_on:
      - db
    command: npm run start:prod

  db:
    image: postgres:latest
    container_name: stores-db
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: fan
      POSTGRES_PASSWORD: lupa_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
